name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        description: 'Version tag:' 
env:
  NODE_VERSION: 16.17.1
  PHP_VERSION: 8.1
jobs:
  docs-publish:
    if: github.event.inputs.tag != ''
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-
      - name: Generate Docs
        run: |
          composer install
          npm run document-check
          npm run document
        env:
          SOURCE_TAG: ${{ github.event.inputs.tag }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.phpdoc/build
