name: release-automated
on:
  push:
    branches: [ master, release, alpha, beta ]
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.tag.outputs.current_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine tag on current commit
        id: tag
        run: echo "::set-output name=current_tag::$(git describe --tags --abbrev=0 --exact-match || echo '')"
  publish-docs:
    needs: release
    if: needs.release.outputs.current_tag != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.release.outputs.current_tag }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
      - name: Generate Docs
        run: |
          npm ci
          npm run document-check
          npm run documentation
        env:
          SOURCE_TAG: ${{ github.event.inputs.tag }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.phpdoc/build
