name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        description: 'Version tag:' 
env:
  NODE_VERSION: 18
  PHP_VERSION: 8.1
jobs:
  docs-publish:
    if: github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Generate Docs
        run: |
          composer install
          npm run document-check
          npm run document
        env:
          SOURCE_TAG: ${{ github.event.inputs.tag }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.phpdoc/build
